# Site settings
email: erikaeburdon@gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Erika's Blog
description: Software Engineering Blog with Tutorials. Created by Erika Burdon. Live examples hosted at erikaburdon.ca.
# url: "http://eburdon.github.io"
url: ""
twitter_username: OneEaredMusic
default_img: 

# Profile settings
name: Erika Burdon
profile_img: 
profile: null
social: 
github: eburdon

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
